= Tangential Developer Docs

== *Required Edits - Todo*
* Deploy Functions before the first 'ng serve' so users can log in.

== Intro
This document describes how to use this project as a bootstrap for your own application. We'll walk through cloning the Tangential Demo repo into your own working directory, initializing your own git repo, and then configuring the project.

*Be aware* that you should be cloning the https://github.com/ggranum/tangential-demo[Tangential-Demo] project, NOT https://github.com/ggranum/tangential[Tangential] itself. The demo project is essentially this project, except everything living under 'src/libs' is imported via NPM. Which makes updating your code with Tangential's changes quite easy, as opposed to nearly impossible.

You might also note that the following steps we break the connection between the Tangential Demo repository and your new project - this is intentional, as we'd rather avoid issues associated with upstream merges - you'll receive updates to your Tangential-based app via NPM rather than attempting to merge a painfully large code base. This frees us here at Tangential from having to be as cautious with adding new features, allowing us to move faster, which allows you to get more sweet time saving tools.

We'll add an 'Advanced' section to cover upstream merges eventually, but for now we're running with the assumption that once you have bootstrapped your project and have been hacking for a couple days, an upstream merge would be a living nightmare. It's not completely true, but it's close enough - especially if you don't work with upstream merges very often.

== What this document covers

We're going to walk though creating a new project that matches our Demo application at https://tangential-demo.firebaseapp.com. This demo application contains everything you see when you browse around, and also Analytics and some advertising.

If you don't wish to use a feature, simply set it to disabled in the project configuration when you get to that point.

== Prerequisites / First steps:

Before we get started, you'll need to create a few accounts and gather some configuration items - private keys, database settings, etc. We'll walk you through each.

First things first: let's choose a project name.

=== Choose YourProjectName

So obvious, right? In fact, there's a good chance you've already cloned this repository into a directory named the way you want your project to be named. If so, great!

If not, try to pick a name that matches what you want your website to be named. Because we've kindly templatized this document, so you can make your life just a little bit easier by doing a find and replace on '${yourProjectName}' (no quotes).

Doing this will make any web links actually work and any bash commands (etc) execute, assuming you follow along and name your external projects and such in line with our suggestions.

* Find and replace ${your-project-name} with your actual snake-cased project name.

We will assume that you will be using `your-project-name` for your production environment, and `your-project-name-dev` for your test environment. These names relate to your analytics settings and your Firebase Database settings, so using names that can used consistently across services is helpful. This means straight-up ascii, no spaces, no leading numbers, etc. Generally, make it a url-safe string that doesn't require escape characters and you *should* be ok.

Side note: If your project name is common, Firebase will issue you an identifier that differs from your project name. Which will cause your Firebase-hosted urls to differ from the links we provide you here. We expect you can update the links with a find-replace accordingly, but we wanted to call it out to help avoid confusion.

=== Set up required Global Tools

Git:: Source control. https://git-scm.com/downloads

Node 9+:: For all the things: https://nodejs.org/en/download/, or google how to install it with HomeBrew, apt... whatever the kids use nowadays.

Gulp:: Used for the build process. Once NodeJs is installed and on your path, run: `npm install gulp-cli`.

That's right. We recommend against using global NPM installs. It only takes one crazy to debug version-related bug to convince most normal humans to join us in this odd notion. Using `npx gulp` is just safer than dealing with version issues between projects.

Instead of global installs, we recommend using npx where possible, or (if you realllly need to have a one-word command) creating aliases to locally installed versions of tool libraries. If npx doesn't work, a distant third option would be to reference the locally installed dependencies via scripts in the package.json file.

We realize our opinion on global installs is not universal, but experience (oh, such painful experience) leads us to prefer the use of aliases over global installs.

If you are super lucky and always get to use the latest and greats versions of everything, then by all means, use global installs. For the rest of us, there are npx, aliases and local dependencies:

As an example, to create aliases for the tools used by this project, execute the following in your terminal:

```bash
echo source ~/.bash_aliases >> ~/.bashrc
echo alias firebase="./node_modules/.bin/firebase" >> ~/.bash_aliases
echo alias ng="./node_modules/.bin/ng"  >> ~/.bash_aliases
source ~/.bash_aliases
```

Just remember that `npx firebase` works perfectly fine.

Or for ZSH:

```zsh
echo source ~/.zsh_alias >> ~/.zshrc
echo alias firebase="./node_modules/.bin/firebase" >> ~/.zsh_alias
echo alias ng="./node_modules/.bin/ng"  >> ~/.zsh_alias
source ~/.zsh_alias
```

The use of an aliases file is optional, but often calling `source` on ~/.bashrc repeatedly isn't completely side effect free (e.g. `path` becoming very, very, very long), and who has the energy to fix that?

The above use of aliases does restrict the use of these tools to the base directory of active projects. In practice this is rarely a problem.

On the off chance it becomes a problem, it can be solved via NPM scripts, which are provided in the package.json for the Tangential and Tangential Demo projects. For example, to call `ng serve` via the script you instead call the npm script we've provided (see 'scripts' in link:package.json[]):

```bash
npm run ng serve
```

Which is exactly(?) equivalent to just using npx:

```bash
npx ng serve
```

Which didn't exist when this documentation was first created. Yay progress!

If you prefer (we're cautious, but not zealots), you can install the tools required by Tangential globally with the following:

```bash
npm install -g firebase-tools
npm install -g @angular/cli
```

Note: If you have never installed any of these tools, move along, there's nothing to see here... Ah, still here. Well, we just want you to know, if you're not already aware, that re-running global installs won't typically hurt anything - or, more specifically, it *shouldn't*, as it will just update you to the most recent release version. However, we'd like you to keep in mind any global tools you upgrade, in case something breaks when you go back to working on other projects. It can be pretty hard to trace where errors come in, especially when you forget that you upgraded something a couple days previous.


=== Optional-ish: Create your Github repo
Create a github repo '${your-project-name}'.

GPLv3 means sharing your modifications, so your project really should be public. Of course, you can share your modifications however you like, Github is just a super easy way to do it.

Don't want to share? Contact us for licensing, we'll get your sorted. Or help us hit our 'MIT!' goal on https://www.patreon.com/tangential[Patreon], and help yourself, too.

=== Set up Firebase

Not optional, unless you plan on writing alternate backend services that match our interfaces - and if you do, we really hope you contribute them back to Tangential!

We'll be creating two Firebase projects. One for development and one for production.


==== Create your projects

Navigate to https://console.firebase.google.com/. If you've never signed up, you'll need to do so.

. Create your first project using the name: ${your-project-name}.
. Create your second, dev project using the name: ${your-project-name}-dev.


==== Configure the projects

. Navigate to https://console.firebase.google.com/project/${your-project-name}/authentication/providers
. Enable 'Email/Password' and 'Anonymous' login methods.
. If you wish to allow other login methods, enable them now. As of the time of writing, Tangential does not provide out of the box support for any of the other methods, but we certainly plan to.
. This is where you'll add authorized OATH domains as well - e.g. if you're testing on a device that connects to your development machine via the address https://192.168.1.88:4200, you'll need to add that host here.

Repeat the same steps for your development project:

. Navigate to https://console.firebase.google.com/project/${your-project-name}-dev/authentication/providers
. Enable 'Email/Password' and 'Anonymous' login methods.


=== Optional: Set up your Analytics 'Account' and 'Properties'
Setting up Analytics is optional, and can be performed at a later time as well.

First up, https://analytics.google.com/analytics[create] your new Google Analytics account, if you haven't done so already. Once you've linked your Google account and filled in all the joyful info required, we'll set up a new "Account", which will contain two "Properties". The Account is actually subsidiary to your overall analytics account (confused yet?): you can have up to 50 accounts, and each account can hold 50 properties. Each property is, generally, a site. If you host on different domains for each language you support, for example.

We are going to organize such that your Account has two Properties, for now. The Account will align with our 'dev' and 'prod' arrangement.

In the future you might add a 'test' environment for running integration tests, complete with a test specific Firebase project and Firebase Hosting. In order to validate that the analytics are working as expected, you could add a third Property, pointed at your Firebase Hosting domain for this 'test' environment.

For now, however, let's just...


==== Figure out how to get to the Admin settings

Navigate to https://analytics.google.com/analytics/web/?authuser=0#management/Settings/. If you don't have an account, go ahead and create one. Once you're signed in, make sure you're on the above page - it is the Account Administration page. If you're not on that page, look down and left, for the standard 'configuration gear' icon. Clicking on that will also bring you to the Account Administration page.

==== Create a new Account for your Project

Choose 'Create new account' from the account dropdown.

In the New Account page, create your Account Name. If you are planning to host multiple _related_ sites, this account name will become the 'parent' of each of those sites.

We're going to start by creating a Google Analytics 'Property' for the dev site.

Set the Website Name input to `${your-project-name}-firebase-dev`. We add the `-firebase` to the name because you will (potentially) have two URLs for each site: the default firebase hosting URL (https://${your-project-name}-dev.firebaseapp.com/) and your own custom domain, such as `https://dev.${your-project-name}.com`. Most likely you'll only have two values for your production domain, but for consistency etc etc whatever, amen.

Set the Website URL to `https://${your-project-name}-dev.firebaseapp.com`.

You will need to determine which additional settings make sense to you.

When done configuring the 'property', click 'Get Tracking ID'. Accept the terms (if you do, of course) and take note of tracking number - it should look something like 'UA-12345678-1'.  Make sure to label it so you know which account it relates to later.

Don't close this browser window yet, you'll need it for the next step:

==== Add Another GA Property for Prod

Your production site will obviously get its own custom domain in the future, but for now we'll set the property up using the Firebase hosting domain.

Returning to the browser window with your Google Analytics Tracking ID, click on the 'PROPERTY' dropdown near the top left - directly to the left of the Tracking ID, and under your Project Name. Choose 'Create new Property. Set the Website name to `${your-project-name}-firebase`, and the Website URL to `https://${your-project-name}.firebaseapp.com`. Set the industry however you wish, and click 'Get Tracking ID'.

Take note of the resulting Tracking ID into your scratch file, as before.

As you may have noted, the Tracking IDs within an account are sequential in the last digit.


== Gathering private keys, Tokens, Ids and configurations
We're going to gather information for Firebase and Google Analytics into a https://www.jetbrains.com/help/webstorm/2017.1/scratches.html[scratch] file. If you use WebStorm, hit ['⇧⌘N' (mac) / 'Ctrl+Shift+Alt+Insert' (other)] to create one now.


=== Google Analytics
Copy your two Analytics Tracking IDs into your scratch file, if you like.

=== Firebase Project Ids
If you're lucky, and your project name is unique, Firebase gave you your project name as your project ID. If not, your Project ID is probably something like '${your-project-name}-2fb4f`. Alas, it's your project ID we actually require.

These IDs can be found on the general settings page for your Firebase Projects. In fact, they are actually part of the URL for each of your projects, which makes it weird that we're adding some links below and hoping they work, but hey, we're optimists:

* Production: https://console.firebase.google.com/project/${your-project-name}/settings/general/
* Development: https://console.firebase.google.com/project/${tangential-demo}-dev/settings/general/

If those links don't work, you can go to the console (https://console.firebase.google.com) and follow the provided link to each project.

Note these project IDs down in your scratch file.

==== An aside: Firebase names versus identities

On your Firebase Project's General Settings https://console.firebase.google.com/project/${your-project-name}/settings/general/[page], you'll see a list of 'names'. Three of them: `Project name , `Public-facing name` and `Project ID`.

If your `Project ID` differs from your `Project name`, you will notice that the links we're providing here in these directions don't quite match up. That's because Firebase, for obvious reasons, uses the Project ID and not the name for links and whatnot. If you want to make the links 'look right' and you're viewing this file in an editor, you can fix it with find and replace:

* Find and replace `https://console.firebase.google.com/project/${your-project-name}-dev` with your actual development Firebase Project URL.
* Find and replace `https://${your-project-name}-dev.firebaseapp.com` with the correct version
* Find and replace `https://console.firebase.google.com/project/${your-project-name}` with your actual production Firebase Project URL.
* Find and replace `https://${your-project-name}.firebaseapp.com` with the correct version

Note that the order that you execute those find-replace operations does matter.

Now, back to gathering info...

=== Firebase Private Keys

Each Firebase project has what is called a 'Service Account Key'. This is used for performing administrative functions, like uploading users, or pushing the initial database template.

For each project, navigate to the service accounts settings page and download a private key file, by clicking on 'Generate New Private Key'. Save it somewhere private and safe.

* Production: https://console.firebase.google.com/project/${your-project-name}/settings/serviceaccounts/adminsdk
* Development: https://console.firebase.google.com/project/${your-project-name}-dev/settings/serviceaccounts/adminsdk


We now have everything we need to rock. Time to do just that.

=== Firebase web app configuration

Copy the Firebase web app config from the general settings page into the scratch file. You'll need to click the red 'Add Firebase to your web app' button on the following pages, and copy out only the `config` value - see the example below the links. You will need to add quote marks (") to the keys to make it valid json.

* https://console.firebase.google.com/project/${your-project-name}-dev/settings/general/
* https://console.firebase.google.com/project/${your-project-name}/settings/general/

Example:
```json
{
    "apiKey": "39_Character_Base64KeyGoesHere",
    "authDomain": "your-project-name.firebaseapp.com",
    "databaseURL": "https://your-project-name.firebaseio.com",
    "projectId": "your-project-name",
    "storageBucket": "your-project-name.appspot.com",
    "messagingSenderId": "00000000000"
  }
```

== Clone and initialize the project

The next few steps center around applying the information gathered in the previous steps to a new project. We're going to :

* Clone the project locally
* Run a few bash commands to create local configuration files (that should NOT be committed to source control)
* Edit our configuration file,
* Verify the configuration
* Deploy our users and database template to our Firebase development project
* Deploy our users and database template to our Firebase production project
* And, finally... profit.


=== Clone wars
Clone the project and then make it your own (remember! Tangential-Demo, NOT plain-old Tangential):

```bash
git clone git@github.com:ggranum/tangential-demo.git ${your-project-name}
cd ${your-project-name}

# Kill off the connection to tangential-demo and initialize your own repo (remove the _XX to run the next command - we're being cautious, in case your above change-directory command failed):
rm_XX -rf .git
git init
git add .
git commit -m "Bootstrapping from Tangential Demo (https://github.com/ggranum/tangential-demo)"

# Optional: Go create a repo on github so you can push:
# git remote add origin git@github.com:${you}/${your-project-name}.git
# git push -u origin master
```

=== Mandatory NPM dependency install step:

Standard all the way:

```bash
# Install all the things
npm install
```

This step also uses the NPM `post-install` script to invoke an `npm install` in the `./functions` subdirectory, as required by https://firebase.google.com/docs/functions/[Firebase Functions].


=== Initialize local configuration files
There are a number of things you don't want committed to public source control. There are a smaller handful of things you don't want committed to source control, period, even if you're using an internal repository specific to your company.

Most of the project configuration falls into the latter category. We've got passwords, we've got private keys, we've got... you get the idea.

To solve this problem, we have created a .gitignore target for files named `**/*.local.*`. Which is to say, any file that has '.local.' in the name won't be committed to source control... iff you are using git. If you're not using git, you should really consider taking a look at the `./.gitignore` file(s) in the project and emulating them in your own version control syntax.

Ok! Warnings given. Now, initialize your various local configuration files:

```bash
gulp project:init
```

This should create a couple of files:

${projectRoot}/config/project.local.json:: Project configuration - includes Firebase settings, analytics settings, etc., for each environment.
${projectRoot}/config/users.local.ts:: Auto-generated file that is useful for running Integration tests. Import this file into your test class to avoid having to hard-code user ids and passwords into your integration test suite.
${projectRoot}/config/dev/firebase-adminsdk-private-key.local.json:: An empty stub for your Firebase Service Account Key, for the Development environment.
${projectRoot}/config/prod/firebase-adminsdk-private-key.local.json:: An empty stub for your Firebase Service Account Key, for the Production environment.
${projectRoot}/environments/environments.local.json:: Configuration settings for each environment that are imported into your project by Angular CLI build targets.
${projectRoot}/.firebaserc:: "Normally" created by either running `firebase init` or `firebase alias...`. We create it for you because we can, and because if you run firebase init you will destroy some rather important configuration settings (well, not destroy, because you can always revert to your last commit... you did commit to source control, right? Right!? :~) ). The .firebaseRc file contains your project alias definitions for the Firebase-cli tool. The aliases are how we will be able to run commands like 'firebase use dev' later, instead of having to type out your entire firebase project id each time.


Our next steps are to update project.local.json with our gathered data, provide some valid email addresses for our users, and copy our firebase private keys into the correct locations.


=== Firebase and Analytics Configuration

Open up the `${projectRoot}/config/project.local.json` settings file. Take a quick scan. Some important highlights:

initialized:: Should currently be false. This will be set to true automatically when your configuration passes validation in the next step.
environments:: You have two to start with: dev and prod. Probably don't consider playing with these names until you already have a working app. And then... probably still don't. But feel free to add other environments at that point, if you need.
suppressAds:: You probably don't want to show ads in your development environment most of the time, lest you accidentally click on one. Setting this to true will suppress the ads, and if the ad container isn't dynamicly sized, it will provide a spacer with a colored background to indicate where the ad _would_ be, were it not suppressed.
production:: If true, enables certain optimizations. (calls Angular's `enableProdMode();` function in `src/main.ts`).
googleAnalytics:: Pretty self-explanatory. Disable if you don't want it. Gulp build targets will fail if you leave this enabled with the default tracking ID.
firebase:: All paths are relative to the `${projectRoot/config/` directory (more accurately, they are relative to the `basePath` value specified in the root of this json object). We'll explain much of this in a seperate section.
projectUsers:: When you start the app the first time, you'll want to be able to sign in to do things. You probably also want to run integration tests.  And we want a demo! So here are three basic user accounts. We'll discuss some important characteristics about these projectUsers in the next sections.

For our next two or three steps we're going to update this file with good values.

==== First, copy your firebase configurations over from your scratch file
Copy over the firebase config settings from your scratch file into each environment - that block of settings that includes `messagingSenderId`.

==== And your Firebase Service Account Keys
Copy the contents of your service account private keys into their respective files:

* ${projectRoot}/config/dev/firebase-adminsdk-private-key.local.json
* ${projectRoot}/config/prod/firebase-adminsdk-private-key.local.json

==== Aaand your Google Analytics tracking ids

The two of them, copied right into the project.local.json file under `environments.dev.googleAnalytics.trackingId` and `environments.prod.googleAnalytics.trackingId`. If you've forgotten which is which, 'dev' should be the one that ends in '-1', and prod in '-2', since they are sequential, and that was the order we suggested you create them.

==== Finally, Edit your user accounts

If you choose to modify the UID values (e.g. 'Administrator') you will need to make adjustments to the `database.rules.json` and `database.init.json` files. So, don't do that yet. In fact, we'd recommend you just don't do it at all, and once you're up and running you use the Admin console to create new accounts and delete the ones you don't want.

However, adding new users *is* an (easy-ish) option. And, if you want more users so soon, it's probably for testing purposes. Which means you WILL need to create them 'automagically' (without having to log in each time you reset the database). So you'll probably want to add them to the project.local.json file, and grant them rights in the database template (`database.init.json`) as well.  Or even create a NEW database.init.json file, specifically for testing, and update the dbTemplateFilePath and rulesFilePath values for the environment. All totally possible. But out of scope at the moment!

Now you know what to look for later - for now, let's just give our existing users valid email addresses. That's it!

Firebase email/password login credentials don't _require_ any email validation, but we'd still like to use real email addresses. Of course, getting a handful of email addresses can be annoying. Thankfully, if you have a Gmail account, you can just add a `yourEmail+whatever@gmail.com` and viola, all the additional free email addresses you could ever dream of. All of them redirected to yourEmail@gmail.com, of course. Usually good, but sometimes possibly bad, if you use your personal email and then start testing your password resets or somesuch. Just a caveat for you to be aware of.

So, to finally do something here, go ahead and provide valid email addresses for each of these accounts. Don't worry about anything else - the password field will be populated automatically in the next step, and not in a file that gets pushed to git.

If you have a Gmail Account:

* Find and replace `example.com` with `gmail.com`
* Find and replace `example` with `yourGmailName` (the part before the '@')

Otherwise

* Replace each email address with a valid email address. If you hate that idea, our validation step only checks that each address is a spec-compliant email address that doesn't contain the word 'example'.


=== Validate all the things

Any time you make changes to the project.local.json file, you should run the update-local task. This re-generates the user.local.ts and environments.local.ts files. You can (and should) follow that up with the validate task, which will attempt to prevent invalid configuration settings from ruining your day.

[source,bash]
----
npx gulp project:update-local
npx gulp project:validate
----


=== Initialize our remote assets - which is to say, Firebase.

We're assuming that you've never used these Firebase accounts. We do attempt to take a backup before blowing away data - in fact, we try to identify if there is data present, and we make you use a `--force` flag if we detect existing data.
However, if you have existing data in your Firebase accounts, please go back it up somewhere. We'll feel really, really bad if you file a bug about how your data got wiped out, and we'll probably even try to fix the bug... but your data will still be gone, and the limit of our response really will be limited to feeling bad and maybe fixing the bug. So MAKE SURE your data is safe. Because this next task is intended to replace it with the contents of the `${projectRoot}/config/database.init.json` file.

[source,bash]
----
# Init the development project
gulp firebase:push-project-users
gulp firebase:push-database-template
firebase use dev && firebase deploy --only database

# Init the Production project
gulp firebase:push-project-users --prod
gulp firebase:push-database-template --prod
firebase use prod && firebase deploy --only database

----

Note that 'firebase deploy --only database' is somewhat misleading: It is deploying your database *rules*, not your database.

The user accounts we pushed can be viewed here:

* Development: https://console.firebase.google.com/project/${your-project-name}-dev/authentication/users
* Production: https://console.firebase.google.com/project/${your-project-name}/authentication/users

The rules we pushed can be found here:

* Development: https://console.firebase.google.com/project/${your-project-name}-dev/database/rules
* Production: https://console.firebase.google.com/project/${your-project-name}/database/rules


== Short pause for effect

The application is at an interesting point now: It is, generally speaking, in the state it will usually be in while you are developing. That is to say, if you sit down three days from now and make a few changes, this is the state the app will be in:

* Database populated with real rules and data.
* Ready to build and deploy, but outstanding code changes not present in your Firebase Hosting deployment.

What we're saying is, you'll do everything previous to this point only very rarely, but you'll find yourself repeating the following steps quite often.

So, congratulations with completing the Bootstrap! The following steps are all things you'll find yourself doing nearly every time you edit your project.

=== It's time to build build build

With our database initialized, we can now start up the application on a local server. Even the local server goes out to our remote firebase service though, hence why we require a the database to be initialized. Yeah, no deserted island development mode here, at least not yet. It's a great goal, but fantastically time-consuming in real life. (that said, if our consumers demand it, we'd absolutely love to implement it!)

So, let's run locally, using the https://github.com/angular/angular-cli[Angular CLI] commands:

[source,bash]
----
npx ng serve --host 0.0.0.0 --port 4200 --configuration dev
----

And open your browser to http://localhost:4200. After a moment or three, you should see the Tangential demo home page. Congratulations, you're nearly to the end!

Regarding the ng serve command, two things to note. We used --host 0.0.0.0 in order to "listen on all endpoints". With this setting, your computer is now listening for other computers on the same network for connections: you can (depending on firewall settings, of course) connect to your current dev environment with your smart phone or tablet, for example.

Second, we specified the port number. Now, 4200 is actually the default port, so in this case specifying it did nothing. However, you can make your testing life a bit easier by using different port numbers for each environment, and for each Firebase App you develop. By using a separate port number you can let your test browsers 'remember' your passwords, and you won't end up with a list of a dozen or more users all registered to 'localhost:4200'.

One final note on running locally: We haven't deployed our 'Cloud Functions' to Firebase yet. This means a few of our 'database triggers' (in this case, yes, but Firebase Cloud Functions are much more than just triggers, generally speaking) won't be running in the background. If you do continue to use and develop against this bootstrap, then you will almost certainly find yourself writing new Cloud Functions - and you, too, will get so used to everything 'just updating on save' that you might very well forget to you have to deploy the Cloud Functions each time you change them!

Let's move on to an actual deployment - just one more step to get our new app live on the public web.

=== Deploy to your Development Environment

The grand finale approaches.

We're going to run an 'AoT' - 'Ahead of time {compile}' build. This differs from non-aot builds in that the code is not being built on the fly, in the browser, each and every time the page is refreshed. At some point you should point a smart phone at a non-aot and an aot build. It's an impressive difference in load times. Compiling on the fly is expensive.

AoT builds also catch some errors that your normal 'ng serve' won't. It attempts tree-shaking (getting rid of unused code), and other optimizations. Let's run one now:

```bash
ng build --aot -oh=all -dev
```

We've explained the aot flag, but not the -oh=all. The -oh flag refers to the 'hashing strategy'. This allows your page to 'break cache' when you update your project. Your Angular bundles (artifacts produced by the build) will get hashed extensions, so that when end-users visit your site they get the fresh bundles, not the old stale ones.

Once the build is done you should have a nice summary of all the bundles Angular created - don't panic, those sizes you see in the output are _uncompressed_ values. They are much, much smaller when served.

You can explore the result of the build by taking a look in your ${projectRoot}/dist` directory.

And, you can _deploy_ the result of the build by running ...

```bash
firebase use dev && firebase deploy
```

Magic.

Your development environment is now deployed!

You can see your site at the URL that the command writes to the console, which should be something like https://${your-project-name}-dev.firebaseapp.com.

=== Now to production!

```bash
ng build --aot -oh=all -prod
firebase use prod && firebase deploy
```


== Your app awaits

Tangential is now bootstrapped, and it's time to start making it your own.

. The first four files you'll likely be interested in:
.. `./src/index.html`
.. `./src/theme.scss`
.. `./src/app/main/main.component.ts`
.. `./src/app/features/casa/home/home.page.ts`

You can sign in to your web app instance(s) using any of the user accounts found in `${projectRoot}/config/users.local.ts` for the associated environment.

We will cover how to use the various Tangential features and widgets in more detail in the coming weeks. For now, we leave you with a set of links to the many, many great sites out there that exist to help with Angular and Firebase.

Thanks, and Good luck!

=== Some useful commands:

You'll probably want to run unit tests, and it's nice to have a simple list of commands to jump to... so here it is!

`ng serve --host 0.0.0.0 -p 4200`:: Also, `ng serve --help`. This is the command we tend to start our development day with. It will build in the background while you make code and style changes. Fair warning: like any compiler it can't always catch the full breadth of some code changes. You may occasionally need to stop and restart the server to 'fix' odd behavior created by such bad state. It's rare enough that, when it happens, you'll likely blame something else first!
`ng build --aot -prod -oh=all`:: Pre-release build, also should be run occasionally to check for AoT build errors (especially if you're editing routes!). AoT builds will find bugs in your templates that you might not catch with just browsing your app in 'serve' or runtime-compile mode.
`firebase list`:: Display a list of all your Firebase projects, and the one that's currently 'in use'.
`firebase use dev` and `firebase use prod`:: We run these prior to a deploy, to ensure our artifacts land in the right firebase project.
`firebase deploy`:: Also, `firebase deploy --help'. This command pushes all of your firebase artifacts to the 'in use' Firebase project. For Tangential, this means Hosting (contents of `./dist` directory), Database (*rules only!*), and Cloud Functions. Push your database template (when you want to destroy your data!) with:
`gulp firebase:push-database-template --dev`:: DESTROY your current data and replace it with whatever is in `./config/database.init.json` (assuming you haven't changed defaults). There is also a --force flag, for overwriting data (yes, we exaggerate in our first sentence here - but you really shouldn't run this command unless you want to reset your database).


=== Link-y goodness

==== Angular

AngularIO - https://angular.io/:: The best site for getting started with Angular. Hit their Guides and walkthroughs, or jump directly to the https://angular.io/docs/ts/latest/api/[API] for specifics.

Angular CLI - https://github.com/angular/angular-cli:: All the `ng foo` commands you have available from your local Terminal window.

Angular Material -- https://github.com/angular/material2/:: These poor developers, sitting at the end of a massive pipeline of new tech. By the very nature of what this team is doing, the Material project is the slowest mover of them all. Think about all the things they have to integrate and test! Also, the Material team doesn't seem to focus on mobile so much (they keep using container-based scrolling, which prevents the address bar from hiding in mobile browsers). With those caveats in mind: if you need widgets, these are high quality and supported by the overall Angular ecosystem.

https://blog.thoughtram.io/angular/2016/10/13/two-way-data-binding-in-angular-2.html[Thoughtram]:: Blog and courses, many written by Pascal Precht, an core Angular developer. Always well written and enlightening. The courses are probably just as amazing, but we've not taken them.



==== Firebase

Docs Homepage - https://firebase.google.com/docs/:: A rather broad target, you might want to choose a more specific link from the following selection
The 'Web Guide' - https://firebase.google.com/docs/database/web/start:: Tangential is using the Web API on the client, so this is where you'll spend a lot of your reading/learning time (if you haven't already, that is).
Web API - https://firebase.google.com/docs/reference/js/ :: The API docs for the Firebase Web client.
Admin Guide -- https://firebase.google.com/docs/database/admin/start:: Once you've read the Web Guide you will find you can skip large portions of this guide, but there are definitely some Admin-specific tidbits in here.
NodeJS Admin API -- https://firebase.google.com/docs/reference/admin/node/:: Incredibly similar to the Web Client API, except where it's not.


==== Google Analytics

Google Analytics Support Center - https://support.google.com/analytics/?hl=en#topic=3544906:: Straight from the source. Google's own help system contains a vast amount of useful information, both text and video. A great place to get started if you're already a believer ;~)

Side note for those new to Analytics:: We frequently equate (or at least closely associate) 'SEO' and 'Analytics' in our documentation. It's not *technically* correct to do this, but it's somewhat normal, once you jump into the field. SEO is Search Engine Optimization, which is absolutely, unquestionably a complete field in it's own right. Analytics is, again, it's own field - it is the field we use to measure the effectiveness of, not just our SEO efforts, but our overall marketing effectiveness. You could certainly do SEO without measuring anything, and you could measure without doing any optimization. Generally speaking, however, you're going to do both if you want to excel. The first step for so many of us is to start with minor SEO, combined with simple analytics. Hence, these two things are very strongly coupled in many minds.

https://www.groovehq.com/blog/seo-for-startups[The basics], Or "why should I do analytics and SEO?":: GrooveHQ has a most amazingly open and clear blog describing their journey from zero to major industry competitor in the small business Help Desk space. If you don't understand or feel like Analytics and SEO are either pointless or, as CEO and Founder Alex Turnbull says, 'scammy', you should start with this article.


== Other notables

=== Favicon and Home Screen Icons

http://www.favicon-generator.org/ is a pretty nifty tool to help you take your high-quality png or jpg images and turn them into icons for various devices.



