= Tangential

Live demo available https://tangential-a8ee8.firebaseapp.com/[here].

== The framework you use is orthogonal to the problem you're trying to solve.

We developers love our frameworks. But, at the end of the day, a framework is just another hammer in the toolbox. If it doesn't let us build our app, it's worthless - or worse. And if it does let us build the app, neither end-users nor management is going to care much which framework we use to do it.

Tangential works to bootstrap you past that horrible, boring, re-write the wheel new-project phase. No need to write Yet Another IAM package. Easy to follow steps for connecting analytics, and even advertising. After that, we stay out of your way. You shouldn't have to care learn the guts and nuances of yet another framework just to get set up. Tangential provides examples for all the major functionality you are ever likely to require in an app. And if you do get into a corner, the Angular community is incredibly active. We'll get you sorted.

If you have never tracked user interactions across your site, Tangential can show you how the way using Google Analytics.

If you have never built a site with advertising before, Tangential can introduce you to displaying ads served by Google AdSense. We'll even link AdSense to Analytics and help you figure out what, exactly, a 'conversion' means to you.

We'd love your feedback - and your contributions if you're up for it.

== Features and highlights
Tangential is still very much in early phases. It is growing as we use it to build out our 'proof of concept' slash validation project, https://SnapLog.io[SnapLog.io], which is a fully featured, ad-supported, analytics-enabled, mobile-oriented 'Life Journal'. SnapLog combines a purpose-driven form builder with long term tracking and correlation features (aka 'charts and graphs'), letting users track, for example, their mood and medication use, and correlate the two over time.

Tangential is already a great way to bootstrap your next personal project, or even something slightly larger in scale. For small sites that need to deploy a single web site or web application, but don't want to deal with hosting or implementing user management from scratch, you'll have a hard time finding anything more powerful.

Once we've hit release candidate we will update the project with licensing information. We have chosen to dual license Tangential because we would like to continue to grow it. As donation schemes are rarely successful, this is the only option we know of that has the potential to fund Tangential in the long term. Should some anonymous, glorious, benefactors wish to commit to funding the project for a significant duration we'd gladly shift to MIT licensing.

Below is a list of major features. Do note that many of the widgets and components you find in the Tangential demo are actually available as separate NPM packages. E.g. the Admin Console can be used without committing to using the entire bootstrap.

Firebase Hosted::  One server hosting. With Firebase Functions and some good Firebase Rule hygiene, you don't need a separate authentication server. How nice is that?

Angular Goodness:: Angular 4+, at the moment. We'll keep the project dependencies up to date

Built in IAM console::  Create and assign new roles and permissions. It's basic at the moment, but growing.

Themed:: Customizable Material Design themes.

Logging:: Log to the browser console - you can see the output in the demo if you open your console

Google Analytics:: Connect your Google Analytics account and get clean, easy to follow page and event tracking. don't have an Analytics account yet? We'll walk you through how to create one.

Google AdSense:: We're still creating ad widgets, but connecting AdSense is as easy as adding your AdSense campaign id to the environments.ts file. No idea what we mean? AdSense is Google's ad serving service, and if you want to display ads in your web site or web app, we'll walk you through how to get started.

AoT Compilation:: There are things you can't do if you want AoT to work in an Angular project. We don't do those things, so your project can benefit from pre-compiled code.

Lazy Loaded Modules:: If only administrators can access the Admin Console, shouldn't it only load if the current visitor is an administrator? Exactly.


== Getting Started

If you are interested is using this project as a template for your own component library, check out the link:GETTING_STARTED.BOOTSTRAP.adoc readme.

If you would like to consume Tangential components / widgets in your project, take a look at link:GETTING_STARTED.LIBRARY.adoc

=== As a template for component-library projects

Tangential's build system was adopted from the Material Design team's Material2 project, prior to their merging all their components into a single namespace. Aside from offering a number of useful components, you may find this project to be a useful template to follow if you are attempting to create a component library of your own.

